---
- name: Hello Ansible!
  hosts: all
  become: true
  tasks:
  - name: Hello Ansible!
    shell: echo "Şimdi NGinx kuracazzz"
    
  - name: Ensure nginx is installed
    yum: name=nginx state=present
    when: ansible_os_family == "RedHat"

  - name: Start nginx start
    service: name=nginx state=started
